name: hive_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs), backed by a Hive store.
version: 2.0.2
homepage: https://github.com/cachapa/hive_crdt
repository: https://github.com/cachapa/hive_crdt
issue_tracker: https://github.com/cachapa/hive_crdt/issues
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crdt:
    git: 
      url: https://github.com/teemu-kemppainen/crdt.git
      ref: fix_javascript_compatibility
  hive: ^2.0.4

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.4
